package net.alexandermora.managemoviesprngbt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = "failureTable")
public class FailureRecord {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String topic;
    private Integer key;
    private String errorRecord;
    private Integer partition;
    private Long offsetValue;
    private String exception;
    private String status;
}

