package net.alexandermora.managemoviesprngbt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.joda.time.DateTime;


@DynamoDBTable(tableName = "Rent")
@Data
public class UserRent
{
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute
    private DateTime dateBegin;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute
    private DateTime dateEnd;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String movie;
}
